# Weather Exploration

In [4]:
# Import libraries
import pandas as pd
from datetime import datetime

## This does not work anymore because the json is too big for GitHub. See below for new code to load the data.

In [ ]:
# Load weather data from json
#df_weather = pd.read_json('../weatherdata/data_scraping/scrapedData/scrapedData.json')
with open('../weatherdata/data_scraping/scrapedData/scrapedData.json', 'r') as file:
    data = pd.read_json(file)

In [ ]:
# transform the data to a more usable format
records = []
for station, entries in data.items():
    for entry in entries:
        dt = datetime.fromtimestamp(entry['dt'])
        temp_k = entry['main']['temp']
        temp_c = temp_k - 273.15  # Convert from Kelvin to Celsius
        weather_desc = entry['weather'][0]['description'] if entry.get('weather') else None
        rain_amount = entry.get('rain', {}).get('1h', 0.0)
        snow_amount = entry.get('snow', {}).get('1h', 0.0)
        humidity = entry['main']['humidity']
        wind_speed = entry['wind']['speed']
        records.append({
            'station': station,
            'time': dt,
            'temp_celsius': round(temp_c, 2),
            'humidity': humidity,
            'wind_speed': wind_speed,
            'weather': weather_desc,
            'rain_amount': rain_amount,
            'snow_amount': snow_amount
        })

# Create DataFrame
df = pd.DataFrame(records)

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
# Display first 5 rows
df.head(15)

In [ ]:
# save the DataFrame to a parquet file (!!!!!DO NOT USE UNLESS YOU WANT TO OVERWRITE THE FILE!!!!!)
#df.to_parquet('../../data/weather_data/weather_data.parquet', index=False)

# Explore created DataFrame after transformation

In [5]:
# Load the DataFrame from parquet file
df = pd.read_parquet('../../data/weather_data/weather_data.parquet')

In [6]:
df.shape

(393609, 8)

In [7]:
df.head(15)

,station,time,temp_celsius,humidity,wind_speed,weather,rain_amount,snow_amount
0,Berlin Gesundbrunnen,2025-01-01 00:00:00,4.36,93,11.09,overcast clouds,0.00,0.0
1,Berlin Gesundbrunnen,2025-01-01 01:00:00,4.84,81,11.53,overcast clouds,0.00,0.0
2,Berlin Gesundbrunnen,2025-01-01 02:00:00,5.45,83,11.70,light rain,0.42,0.0
3,Berlin Gesundbrunnen,2025-01-01 03:00:00,5.42,84,11.82,moderate rain,1.33,0.0
4,Berlin Gesundbrunnen,2025-01-01 04:00:00,5.92,84,11.61,moderate rain,2.37,0.0
5,Berlin Gesundbrunnen,2025-01-01 05:00:00,6.53,86,11.95,light rain,0.13,0.0
6,Berlin Gesundbrunnen,2025-01-01 06:00:00,6.59,87,12.80,light rain,0.52,0.0
7,Berlin Gesundbrunnen,2025-01-01 07:00:00,7.21,86,12.91,light rain,0.73,0.0
8,Berlin Gesundbrunnen,2025-01-01 08:00:00,7.00,85,13.43,light rain,0.60,0.0
9,Berlin Gesundbrunnen,2025-01-01 09:00:00,7.56,83,13.76,light rain,0.18,0.0
10,Berlin Gesundbrunnen,2025-01-01 10:00:00,7.61,83,13.64,moderate rain,1.26,0.0
11,Berlin Gesundbrunnen,2025-01-01 11:00:00,7.61,81,13.55,light rain,0.65,0.0
12,Berlin Gesundbrunnen,2025-01-01 12:00:00,7.61,81,13.63,moderate rain,1.09,0.0
13,Berlin Gesundbrunnen,2025-01-01 13:00:00,7.62,83,13.66,moderate rain,1.15,0.0
14,Berlin Gesundbrunnen,2025-01-01 14:00:00,7.20,84,13.77,moderate rain,1.54,0.0

In [10]:
# Display all stations names
df['station'].unique()

array(['Berlin Gesundbrunnen', 'Berlin SÃ¼dkreuz',
       'Berlin Potsdamer Platz', 'Berlin Hbf', 'Paderborn Hbf',
       'Hamm(Westf)Hbf', 'Hamburg Hbf', 'Hamburg Dammtor',
       'Karlsruhe Hbf', 'WÃ¼rzburg Hbf', 'Bietigheim-Bissingen',
       'Berlin-Lichtenberg', 'Berlin Ostkreuz', 'Berlin Ostbahnhof',
       'Berlin FriedrichstraÃŸe', 'Landshut(Bay)Hbf', 'Weimar',
       'Flughafen BER', 'Frankfurt(Main)SÃ¼d', 'Hamburg-Altona',
       'Essen Hbf', 'Frankfurt(Main)Hbf', 'DÃ¼sseldorf Hbf', 'Neuss Hbf',
       'KÃ¶ln Hbf', 'Kassel Hbf', 'MÃ¼nchen Ost', 'MÃ¼nchen Hbf',
       'GieÃŸen', 'Hildesheim Hbf', 'MÃ¼nchen-Pasing', 'Aachen Hbf',
       'MÃ¶nchengladbach Hbf', 'KÃ¶ln Messe/Deutz', 'Erfurt Hbf',
       'NÃ¼rnberg Hbf', 'Bochum Hbf', 'Frankfurt(Oder)', 'Hanau Hbf',
       'Wuppertal Hbf', 'Mainz Hbf', 'Duisburg Hbf', 'Oberhausen Hbf',
       'Gelsenkirchen Hbf', 'MÃ¼nster(Westf)Hbf', 'Dortmund Hbf',
       'GÃ¶ttingen', 'Bielefeld Hbf', 'Herford', 'Stuttgart Hbf',
       'Heidelberg Hbf', 'Darmstadt Hbf', 'Fulda', 'Halle(Saale)Hbf',
       'Aschaffenburg Hbf', 'Bremen Hbf', 'Dresden-Neustadt',
       'Dresden Hbf', 'Hamburg-Harburg', 'LÃ¼neburg',
       'Berlin Zoologischer Garten', 'Potsdam Hbf', 'Berlin-Wannsee',
       'Koblenz Hbf', 'Oldenburg(Oldb)Hbf', 'Hannover Hbf',
       'Braunschweig Hbf', 'Magdeburg Hbf', 'Leipzig Hbf',
       'Berlin-Spandau', 'Augsburg Hbf', 'Cottbus Hbf', 'Plochingen',
       'Trier Hbf', 'Pforzheim Hbf', 'Wiesbaden Hbf', 'Mannheim Hbf',
       'Neustadt(Weinstr)Hbf', 'Kaiserslautern Hbf', 'SaarbrÃ¼cken Hbf',
       'Kiel Hbf', 'Hagen Hbf', 'Wolfsburg Hbf', 'Ulm Hbf', 'Bruchsal',
       'Worms Hbf', 'Ludwigshafen(Rh)Hbf', 'Bamberg', 'FÃ¼rth(Bay)Hbf',
       'OsnabrÃ¼ck Hbf', 'Bonn Hbf', 'TÃ¼bingen Hbf', 'Offenburg',
       'Rheine', 'NeumÃ¼nster', 'LÃ¼beck Hbf', 'Solingen Hbf',
       'Chemnitz Hbf', 'Uelzen', 'Kassel-WilhelmshÃ¶he', 'Regensburg Hbf',
       'Singen(Hohentwiel)', 'Ingolstadt Hbf', 'Freiburg(Breisgau) Hbf',
       'Bad Oldesloe', 'Rosenheim', 'Rostock Hbf'], dtype=object)

In [9]:
df_nuernberg.head(15)

Empty DataFrame
Columns: [station, time, temp_celsius, humidity, wind_speed, weather, rain_amount, snow_amount]
Index: []